function customValidateForm(form){ 
	var CURRENT_STATE = getValue("WKNumState");
	var errorMsg = ""; 

	/*if(CURRENT_STATE == 0 || CURRENT_STATE == INICIO){} 
	if(CURRENT_STATE == GERA_COTACAO_){}
	if(CURRENT_STATE == COTACAO){}
	if(CURRENT_STATE == DEFINIR_VENCEDOR){}
	if(CURRENT_STATE == APROVACAO_4A_ALCADA){}
	if(CURRENT_STATE == EMITIR_PEDIDO_DE_COMPRA){}
	if(CURRENT_STATE == ANALISE_COMPRADOR){}
	if(CURRENT_STATE == FIM){}
	if(CURRENT_STATE == FIM){}
	if(CURRENT_STATE == PRREENCHER_FORMULARIO_OBJETO_REAJUSTE_RECISAO_VALOR_VALIDADE){}
	if(CURRENT_STATE == ANEXAR_MINUTA){}
	if(CURRENT_STATE == VALIDAR_MINUTA){}
	if(CURRENT_STATE == AJUSTAR_DIVIRGENCIA){}
	if(CURRENT_STATE == RECOLHER_ASSINATURA_E_DIGITALIZAR_CONTRATO){}
	if(CURRENT_STATE == GERAR_CONTRATO_PROTHEUS){}
	if(CURRENT_STATE == FIM){}
	if(CURRENT_STATE == APROVACAO_3A_ALCADA){}
	if(CURRENT_STATE == APROVACAO_2A_ALCADA){}
	if(CURRENT_STATE == APROVACAO_1A_ALCADA){}
	if(CURRENT_STATE == FIM){}
	if(CURRENT_STATE == TERMINO_APROVACAO_SISTEMA){}*/
	return errorMsg; 
}
