var AtividadeEnum = {
  INICIO: 4,
  VALIDACAO_ONCOPROD: 5,
  CORRECAO_SOLICITANTE: 7,
  ALCADA_APROVACAO: 8,
  EMITIR_PEDIDO_COMPRA: 23,
  EXCECAO_INTEGRACAO: 25,
  ANEXAR_NF: 29,
  VALIDACAO_ENTREGA: 34,
  FIM: 39,
};