var INICIO = "6";
var VALIDACAO_CLINICA  = "7";
var CORRECAO_SOLICITANTE = "11";
var VALIDACAO_ONCOPROD = "14";
var ALCADA_APROVACAO = "19";
var EMITIR_PEDIDO = "30";
var ANEXAR_NF = "31";
var LANCAMENTO_ABAX = "35";