var CURRENT_STATE = getValue('WKNumState');
var INICIO = "6";
var VALIDACAO_CLINICA = "7";
var CORRECAO_SOLICITANTE = "11";
var VALIDACAO_ONCOPROD = "14";
var ALCADA_APROVACAO = "19";
var EMITIR_PEDIDO = "30";
var ATENDER_PEDIDO = "31";
var VERIFICAR_PRODUTOS = "35";
var EXCECAO_INTEGRACAO = "47";


